const db = {
  products: [
    {
      id: 1,
      name: 'VESTIDO COM MANGAS BUFANTES',
      category: 'ROUPAS',
      rating: 4,
      color: 'floral',
      price: 249.0,
      size: 'M',
      percent: 0,
      details: {
        product: '',
        warranty: '',
        merchant: '',
      },
      image: 'product1',
    },
    {
      id: 2,
      name: 'MOLETOM FORRADO',
      category: 'ROUPAS',
      rating: 4,
      color: 'branco',
      size: 'G',
      price: 518.7,
      percent: 50,
      details: {
        product: '',
        warranty: '',
        merchant: '',
      },
      image: 'product2',
    },
    {
      id: 3,
      name: 'BOLSA COM ZIPPER',
      category: 'ACESSÓRIOS',
      rating: 4,
      color: 'vermelha',
      size: '',
      price: 220.0,
      percent: 0,
      details: {
        product: '',
        warranty: '',
        merchant: '',
      },
      image: 'product3',
    },
    {
      id: 4,
      name: 'CAMISA ARAMIS',
      category: 'ROUPAS',
      rating: 4,
      color: 'branca',
      size: 'M',
      price: 199.9,
      percent: 50,
      details: {
        product: '',
        warranty: '',
        merchant: '',
      },
      image: 'product4',
    },
    {
      id: 5,
      name: 'MOLETOM COM CAPUZ',
      category: 'ROUPAS',
      rating: 4,
      color: 'preto',
      size: 'G',
      price: 255.8,
      percent: 0,
      details: {
        product: '',
        warranty: '',
        merchant: '',
      },
      image: 'product5',
    },
    {
      id: 6,
      name: 'TÊNIS FEMININO HRX',
      category: 'CALÇADOS',
      rating: 4,
      color: 'cinza grafite',
      price: 520.5,
      size: '',
      percent: 0,
      details: {
        product: '',
        warranty: '',
        merchant: '',
      },
      image: 'product6',
    },
    {
      id: 7,
      name: 'VESTIDO TRANSPASSE',
      category: 'ROUPAS',
      rating: 4,
      color: 'rosa chiclete',
      price: 258.9,
      size: 'S',
      percent: 50,
      details: {
        product: '',
        warranty: '',
        merchant: '',
      },
      image: 'product7',
    },
    {
      id: 8,
      name: 'TÊNIS MASCULINO SPORT',
      category: 'CALÇADOS',
      rating: 4,
      color: 'preto',
      price: 599.9,
      size: '',
      percent: 0,
      details: {
        product: '',
        warranty: '',
        merchant: '',
      },
      image: 'product8',
    },
    {
      id: 9,
      name: 'TÊNIS MASCULINO SPORT',
      category: 'CALÇADOS',
      rating: 4,
      color: 'preto',
      price: 599.9,
      size: '',
      percent: 0,
      details: {
        product: '',
        warranty: '',
        merchant: '',
      },
      image: 'product9',
    },
  ],
};
export default db;
