const db = {
  products: [
    {
      id: 1,
      name: 'VESTIDO FLORIDO',
      category: 'ROUPAS',
      rating: 3,
      color: 'floral',
      price: 249.0,
      size: 'M',
      percent: 0,
      details: {
        product: '',
        warranty: '',
        merchant: '',
      },
      image: 'product1',
    },
    {
      id: 2,
      name: 'MOCHILA NOTEBOOK',
      category: 'ACESSÓRIOS',
      rating: 5,
      color: 'vermelho',
      size: '',
      price: 518.7,
      percent: 50,
      details: {
        product: '',
        warranty: '',
        merchant: '',
      },
      image: 'product2',
    },
    {
      id: 3,
      name: 'CAMISA PRETA',
      category: 'ROUPAS',
      rating: 4,
      color: 'preta',
      size: 'M',
      price: 220.0,
      percent: 0,
      details: {
        product: '',
        warranty: '',
        merchant: '',
      },
      image: 'product3',
    },
    {
      id: 4,
      name: 'TENIS ESPORTIVO',
      category: 'CALÇADOS',
      rating: 4,
      color: 'preto',
      size: '40',
      price: 199.9,
      percent: 10,
      details: {
        product: '',
        warranty: '',
        merchant: '',
      },
      image: 'product4',
    },
    {
      id: 5,
      name: 'MOLETOM COM CAPUZ',
      category: 'ROUPAS',
      rating: 4,
      color: 'preto',
      size: 'G',
      price: 255.8,
      percent: 0,
      details: {
        product: '',
        warranty: '',
        merchant: '',
      },
      image: 'product5',
    },
    {
      id: 6,
      name: 'VESTIDO MANGAS BUFANTES',
      category: 'ROUPAS',
      rating: 5,
      color: 'rosa',
      price: 520.5,
      size: 'M',
      percent: 0,
      details: {
        product: '',
        warranty: '',
        merchant: '',
      },
      image: 'product6',
    },
    {
      id: 7,
      name: 'TENIS CORRIDA',
      category: 'CALÇADOS',
      rating: 4,
      color: 'preto',
      price: 258.9,
      size: '42',
      percent: 5,
      details: {
        product: '',
        warranty: '',
        merchant: '',
      },
      image: 'product7',
    },
    {
      id: 8,
      name: 'CAMISA SOCIAL',
      category: 'ROUPAS',
      rating: 1,
      color: 'preto',
      price: 599.9,
      size: 'M',
      percent: 0,
      details: {
        product: '',
        warranty: '',
        merchant: '',
      },
      image: 'product8',
    },
    {
      id: 9,
      name: 'CAMISA SPORT FINO',
      category: 'ROUPAS',
      rating: 4,
      color: 'preto',
      price: 599.9,
      size: 'M',
      percent: 0,
      details: {
        product: '',
        warranty: '',
        merchant: '',
      },
      image: 'product9',
    },
  ],
};
export default db;
